theme: minima 

Mr. Enfield and the lawyer were on the other side of the by-street; but when they came abreast of the entry, the former lifted up his cane and pointed.

“Did you ever remark that door?” he asked; and when his companion had replied in the affirmative. “It is connected in my mind,” added he, “with a very odd story.”

“Indeed?” said Mr. Utterson, with a slight change of voice, “and what was that?”
